name: Main

on:
    push:
        branches:
            - main
        paths:
            - force-app/**

jobs:
    incremental-deploy:
        name: Deploy delta changes
        uses: ./.github/workflows/incremental-deploy.yml
        secrets: inherit
        with:
            # Note: This requires the merged PR to only have a single commit or merge commit
            baseRef: 'HEAD~1'
            targetRef: 'HEAD'