name: Pull Request

on:
    pull_request:
        branches:
            - main
        paths:
            - force-app/**

jobs:
    incremental-deploy:
        name: Validate deployment delta changes
        uses: ./.github/workflows/incremental-deploy.yml
        secrets: inherit
        with:
            baseRef: 'origin/${GITHUB_BASE_REF}'
            targetRef: 'HEAD'
            validateOnly: true